import { Autocomplete } from './modules/autocomplete';
import { ReportModel } from './modules/report';
import { Modal } from './modules/modal';
import { Result } from './modules/result';
import { MoreResults } from './modules/more-results';

export interface CallSignatures {
    (name: 'admin::changeAddress', p0: Element, p1: string, p2: JQuery<HTMLElement>): void;
    (name: 'admin::commercialReference'): void;
    (name: 'admin::index'): void;
    (name: 'admin::openCompanys', p0: ReportModel, p1: { commercialReference: string }): void;
    (name: 'admin::openCompanys', p0: ReportModel, p1: { tag: string }): void;
    (name: 'admin::openCompanys', p0: ReportModel): void;
    (name: 'admin::remove::email', p0: JQuery<HTMLElement>, p1: JQuery<HTMLElement>, p2: string, p3: string): JQuery<HTMLElement>;
    (name: 'admin::remove::phone', p0: JQuery<HTMLElement>, p1: JQuery<HTMLElement>, p2: string, p3: string, p4: string, p5: string): JQuery<HTMLElement>;
    (name: 'admin::report::dataset', p0: JQuery<HTMLElement>): { datasets: Array<any>, labels: Array<any> };
    (name: 'admin::report::filter', p0: string, p1: ReportModel, p2: Function, p3: boolean): void;
    (name: 'admin::report', p0: Function, p1: JQuery<HTMLElement>, p2: string, p3: string, p4: string, p5: string, p6: string, p7: boolean): void;
    (name: 'admin::report', p0: Function, p1: JQuery<HTMLElement>, p2: string, p3: undefined, p4: undefined, p5: undefined, p6: string, p7: boolean): void;
    (name: 'admin::report', p0: Function, p1: JQuery<HTMLElement>): void;
    (name: 'admin::tag::create', p0: string): void;
    (name: 'admin::tags::view', p0: boolean, p1: string): void;
    (name: 'admin::tags', p0: string): void;
    (name: 'admin::tagsViewer'): void;
    (name: 'admin::viewCompany', p0: Element, p1: boolean, p2: null, p3: boolean): JQuery<HTMLElement>;
    (name: 'authentication::loggedin'): void;
    (name: 'authentication::need', p0: Function): boolean;
    (name: 'autocomplete', p0: JQuery<HTMLElement>): Autocomplete;
    (name: 'billingInformation::need', p0: Function): void;
    (name: 'credits::buy'): void;
    (name: 'default::page'): void;
    (name: 'error::ajax', p0: { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, error: Function, success: Function };
    (name: 'error::ajax', p0: { beforeSend: Function, complete: Function, error: Function, success: Function }): { beforeSend: Function, complete: Function, error: Function, success: Function };
    (name: 'error::ajax', p0: { cache: boolean, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'error::ajax', p0: { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'error::ajax', p0: { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function };
    (name: 'error::ajax', p0: { data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function }): { data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function };
    (name: 'error::ajax', p0: { data: { limit: number, skip: number, tag: string }, error: Function, success: Function }): { data: { limit: number, skip: number, tag: string }, error: Function, success: Function };
    (name: 'error::ajax', p0: { data: { limit: number, skip: number }, error: Function, success: Function }): { data: { limit: number, skip: number }, error: Function, success: Function };
    (name: 'error::ajax', p0: { error: Function, success: Function }): { error: Function, success: Function };
    (name: 'form', p0: Function): GenerateForm;
    (name: 'i18n', p0: HTMLDocument): void;
    (name: 'iframeEmbed'): boolean;
    (name: 'inbox::check'): void;
    (name: 'inbox'): void;
    (name: 'instantSearch', p0: JQuery<HTMLElement>, p1: Function): void;
    (name: 'loader::ajax', p0: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, complete: Function, data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, complete: Function, data: { limit: number, skip: number, tag: string }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { limit: number, skip: number, tag: string }, error: Function, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, complete: Function, data: { limit: number, skip: number, text: undefined }, success: Function }, p1: boolean): { beforeSend: Function, complete: Function, data: { limit: number, skip: number, text: undefined }, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, complete: Function, data: { limit: number, skip: number }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { limit: number, skip: number }, error: Function, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, success: Function }): { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, success: Function };
    (name: 'loader::ajax', p0: { beforeSend: Function, complete: Function, success: Function }): { beforeSend: Function, complete: Function, success: Function };
    (name: 'loader::catchElement'): JQuery<HTMLElement>;
    (name: 'loader::register'): void;
    (name: 'loader::unregister'): void;
    (name: 'modal'): Modal;
    (name: 'moreResults', p0: number): MoreResults;
    (name: 'report', p0: string, p1: string, p2: null, p3: boolean): ReportModel;
    (name: 'report', p0: string, p1: string, p2: string, p3: boolean): ReportModel;
    (name: 'report', p0: string, p1: string, p2: string): ReportModel;
    (name: 'result'): Result;
    (name: 'section', p0: string, p1: string, p2: string, p3: boolean, p4: boolean): Array<any>;
    (name: 'site::buttons'): void;
    (name: 'site::carrousel'): void;
    (name: 'tooltip', p0: JQuery<HTMLElement>, p1: string): JQuery<HTMLElement>;
}
