import { Autocomplete } from './modules/autocomplete';
import { ReportModel } from './modules/report';
import { Modal } from './modules/modal';
import { Result } from './modules/result';
import { MoreResults } from './modules/more-results';
import { GenerateForm } from './modules/form';

export interface CallSignatures {
    (name: 'admin::changeAddress', element1: Element, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::commercialReference'): void;
    (name: 'admin::index'): void;
    (name: 'admin::openCompanys', reportModel: ReportModel, obj: { commercialReference: string }): void;
    (name: 'admin::openCompanys', reportModel: ReportModel, obj: { tag: string }): void;
    (name: 'admin::openCompanys', reportModel: ReportModel): void;
    (name: 'admin::remove::email', element1: JQuery<HTMLElement>, element2: JQuery<HTMLElement>, text1: string, text2: string): JQuery<HTMLElement>;
    (name: 'admin::remove::phone', element1: JQuery<HTMLElement>, element2: JQuery<HTMLElement>, text1: string, text2: string, text3: string, text4: string): JQuery<HTMLElement>;
    (name: 'admin::report::dataset', element: JQuery<HTMLElement>): { datasets: Array<any>, labels: Array<any> };
    (name: 'admin::report::filter', text: string, reportModel: ReportModel, callback: Function, flag: boolean): void;
    (name: 'admin::report', callback: Function, element: JQuery<HTMLElement>, text1: string, text2: string, text3: string, text4: string, text5: string, flag: boolean): void;
    (name: 'admin::report', callback: Function, element: JQuery<HTMLElement>, text1: string, obj1: undefined, obj2: undefined, obj3: undefined, text2: string, flag: boolean): void;
    (name: 'admin::report', callback: Function, element: JQuery<HTMLElement>): void;
    (name: 'admin::tag::create', text: string): void;
    (name: 'admin::tags::view', flag: boolean, text: string): void;
    (name: 'admin::tags', text: string): void;
    (name: 'admin::tagsViewer'): void;
    (name: 'admin::viewCompany', element: Element, flag1: boolean, obj: null, flag2: boolean): JQuery<HTMLElement>;
    (name: 'authentication::loggedin'): void;
    (name: 'authentication::need', callback: Function): boolean;
    (name: 'autocomplete', element: JQuery<HTMLElement>): Autocomplete;
    (name: 'billingInformation::need', callback: Function): void;
    (name: 'credits::buy'): void;
    (name: 'default::page'): void;
    (name: 'error::ajax', obj: { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, error: Function, success: Function };
    (name: 'error::ajax', obj: { beforeSend: Function, complete: Function, error: Function, success: Function }): { beforeSend: Function, complete: Function, error: Function, success: Function };
    (name: 'error::ajax', obj: { cache: boolean, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function };
    (name: 'error::ajax', obj: { data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function }): { data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function };
    (name: 'error::ajax', obj: { data: { limit: number, skip: number, tag: string }, error: Function, success: Function }): { data: { limit: number, skip: number, tag: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { data: { limit: number, skip: number }, error: Function, success: Function }): { data: { limit: number, skip: number }, error: Function, success: Function };
    (name: 'error::ajax', obj: { error: Function, success: Function }): { error: Function, success: Function };
    (name: 'form', callback: Function): GenerateForm;
    (name: 'i18n', document: HTMLDocument): void;
    (name: 'iframeEmbed'): boolean;
    (name: 'inbox::check'): void;
    (name: 'inbox'): void;
    (name: 'instantSearch', element: JQuery<HTMLElement>, callback: Function): void;
    (name: 'loader::ajax', obj: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, skip: number, tag: string }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { limit: number, skip: number, tag: string }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, skip: number, text: undefined }, success: Function }, flag: boolean): { beforeSend: Function, complete: Function, data: { limit: number, skip: number, text: undefined }, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, skip: number }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { limit: number, skip: number }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, success: Function }): { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, success: Function }): { beforeSend: Function, complete: Function, success: Function };
    (name: 'loader::catchElement'): JQuery<HTMLElement>;
    (name: 'loader::register'): void;
    (name: 'loader::unregister'): void;
    (name: 'modal'): Modal;
    (name: 'moreResults', num: number): MoreResults;
    (name: 'report', text1: string, text2: string, obj: null, flag: boolean): ReportModel;
    (name: 'report', text1: string, text2: string, text3: string, flag: boolean): ReportModel;
    (name: 'report', text1: string, text2: string, text3: string): ReportModel;
    (name: 'result'): Result;
    (name: 'section', text1: string, text2: string, text3: string, flag1: boolean, flag2: boolean): Array<any>;
    (name: 'site::buttons'): void;
    (name: 'site::carrousel'): void;
    (name: 'tooltip', element: JQuery<HTMLElement>, text: string): JQuery<HTMLElement>;
}
