import { Autocomplete } from './modules/autocomplete';
import { ReportModel } from './modules/report';
import { Modal } from './modules/modal';
import { Result } from './modules/result';
import { MoreResults } from './modules/more-results';
import { GenerateForm } from './modules/form';

export interface CallSignatures<T> {
    (name: 'admin::changeAddress', element1: Element, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::changeAddress', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::changeCompany', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::changeContract', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::commercialReference'): void;
    (name: 'admin::contactTypes'): { comercial: string, financeiro: string, tecnico: string };
    (name: 'admin::email', text: string, element: JQuery<HTMLElement>): void;
    (name: 'admin::fillCompanyAutocomplete', element: Element, autocomplete: Autocomplete): void;
    (name: 'admin::fillCompanysAutocomplete', xMLDocument: XMLDocument, autocomplete: Autocomplete): void;
    (name: 'admin::index'): void;
    (name: 'admin::openCompanys', reportModel: ReportModel, obj: { commercialReference: string }): void;
    (name: 'admin::openCompanys', reportModel: ReportModel, obj: { tag: string }): void;
    (name: 'admin::openCompanys', reportModel: ReportModel): void;
    (name: 'admin::phone', text: string, element: JQuery<HTMLElement>): void;
    (name: 'admin::remove::email', element1: JQuery<HTMLElement>, element2: JQuery<HTMLElement>, text1: string, text2: string): JQuery<HTMLElement>;
    (name: 'admin::remove::phone', element1: JQuery<HTMLElement>, element2: JQuery<HTMLElement>, text1: string, text2: string, text3: string, text4: string): JQuery<HTMLElement>;
    (name: 'admin::report::dataset', element: JQuery<HTMLElement>): { datasets: Array<any>, labels: Array<any> };
    (name: 'admin::report::filter', text: string, reportModel: ReportModel, callback: Function, flag: boolean): void;
    (name: 'admin::report', callback: Function, element: JQuery<HTMLElement>, text1: string, text2: string, text3: string, text4: string, text5: string, flag: boolean): void;
    (name: 'admin::report', callback: Function, element: JQuery<HTMLElement>, text1: string, obj1: undefined, obj2: undefined, obj3: undefined, text2: string, flag: boolean): void;
    (name: 'admin::report', callback: Function, element: JQuery<HTMLElement>): void;
    (name: 'admin::roleTypes'): { '': string, avancado: string, simples: string };
    (name: 'admin::tag::create', text: string): void;
    (name: 'admin::tags::view', array: Array<any>, text: string): void;
    (name: 'admin::tags::view', flag: boolean, text: string): void;
    (name: 'admin::tags', text: string): void;
    (name: 'admin::tagsViewer'): void;
    (name: 'admin::viewCompany', element: Element, flag1: boolean, obj: null, flag2: boolean): JQuery<HTMLElement>;
    (name: 'admin::viewCompany', element: JQuery<HTMLElement>): JQuery<HTMLElement>;
    (name: 'authentication::loggedin'): void;
    (name: 'authentication::need', callback: Function): boolean;
    (name: 'autocomplete', element: JQuery<HTMLElement>): Autocomplete;
    (name: 'billingInformation::changeAddress', callback: Function, xMLDocument: XMLDocument, obj: undefined): void;
    (name: 'billingInformation::force'): void;
    (name: 'billingInformation::need', callback: Function): void;
    (name: 'credits::buy'): void;
    (name: 'default::page'): void;
    (name: 'error::ajax', obj: { beforeSend: Function, complete: Function, data: { id: string }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { id: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, error: Function, success: Function };
    (name: 'error::ajax', obj: { beforeSend: Function, complete: Function, error: Function, success: Function }): { beforeSend: Function, complete: Function, error: Function, success: Function };
    (name: 'error::ajax', obj: { cache: boolean, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function }): { cache: boolean, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function };
    (name: 'error::ajax', obj: { data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function }): { data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function };
    (name: 'error::ajax', obj: { data: { limit: number, skip: number, tag: string }, error: Function, success: Function }): { data: { limit: number, skip: number, tag: string }, error: Function, success: Function };
    (name: 'error::ajax', obj: { data: { limit: number, skip: number }, error: Function, success: Function }): { data: { limit: number, skip: number }, error: Function, success: Function };
    (name: 'error::ajax', obj: { error: Function, success: Function }): { error: Function, success: Function };
    (name: 'form', callback: Function): GenerateForm;
    (name: 'i18n', document: HTMLDocument): void;
    (name: 'iframeEmbed'): boolean;
    (name: 'inbox::check'): void;
    (name: 'inbox::open', xMLDocument: XMLDocument, text: string): void;
    (name: 'inbox'): void;
    (name: 'instantSearch', element: JQuery<HTMLElement>, callback: Function): void;
    (name: 'link', text: string, obj: { altKey: boolean, bubbles: boolean, button: number, buttons: number, cancelable: boolean, changedTouches: undefined, char: undefined, charCode: undefined, clientX: number, clientY: number, code: undefined, constructor: Function, ctrlKey: boolean, currentTarget: HTMLAnchorElement, data: null, delegateTarget: HTMLAnchorElement, detail: number, eventPhase: number, handleObj: { data: null, guid: number, handler: Function, namespace: string, needsContext: undefined, origType: string, selector: undefined, type: string }, isDefaultPrevented: Function, isImmediatePropagationStopped: Function, isPropagationStopped: Function, isSimulated: boolean, jQuery34105553482942536505: boolean, key: undefined, keyCode: undefined, metaKey: boolean, offsetX: number, offsetY: number, originalEvent: MouseEvent, pageX: number, pageY: number, pointerId: undefined, pointerType: undefined, preventDefault: Function, relatedTarget: null, screenX: number, screenY: number, shiftKey: boolean, stopImmediatePropagation: Function, stopPropagation: Function, target: HTMLAnchorElement, targetTouches: undefined, timeStamp: number, toElement: HTMLAnchorElement, touches: undefined, type: string, view: Window, which: number }): void;
    (name: 'loader::ajax', obj: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: string, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: string }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function }): { beforeSend: Function, cache: boolean, complete: Function, data: { contractType: null, dateEnd: undefined, dateStart: string, period: string, username: undefined }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { commercialReference: string, limit: number, skip: number }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { id: string }, success: Function }): { beforeSend: Function, complete: Function, data: { id: string }, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, owner: string, skip: number, username: undefined }, success: Function }, flag: boolean): { beforeSend: Function, complete: Function, data: { limit: number, owner: string, skip: number, username: undefined }, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, skip: number, tag: string }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { limit: number, skip: number, tag: string }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, skip: number, text: undefined }, success: Function }, flag: boolean): { beforeSend: Function, complete: Function, data: { limit: number, skip: number, text: undefined }, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { limit: number, skip: number }, error: Function, success: Function }): { beforeSend: Function, complete: Function, data: { limit: number, skip: number }, error: Function, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, success: Function }): { beforeSend: Function, complete: Function, data: { username: string }, dataType: string, success: Function };
    (name: 'loader::ajax', obj: { beforeSend: Function, complete: Function, success: Function }): { beforeSend: Function, complete: Function, success: Function };
    (name: 'loader::catchElement'): JQuery<HTMLElement>;
    (name: 'loader::register'): void;
    (name: 'loader::unregister'): void;
    (name: 'modal'): Modal;
    (name: 'moreResults', num: number): MoreResults;
    (name: 'report', text1: string, text2: string, obj: null, flag: boolean): ReportModel;
    (name: 'report', text1: string, text2: string, text3: string, flag: boolean): ReportModel;
    (name: 'report', text1: string, text2: string, text3: string): ReportModel;
    (name: 'result'): Result;
    (name: 'section', text1: string, text2: string, text3: string, flag1: boolean, flag2: boolean): Array<any>;
    (name: 'section', text1: string, text2: string, text3: string, flag: boolean, obj: undefined): Array<any>;
    (name: 'site::buttons'): void;
    (name: 'site::carrousel'): void;
    (name: 'subaccount::list', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'tooltip', element: JQuery<HTMLElement>, text: string): JQuery<HTMLElement>;
}

export interface RegisterTriggerSignatures<T> {
    (name: 'authentication::authenticated', text: string, callback: Function): void;
    (name: 'authentication::logout', text: string, callback: Function): void;
    (name: 'bootstrap::end', text: string, callback: Function): void;
    (name: 'call::authentication::loggedin', text: string, callback: Function): void;
    (name: 'database::error', text: string, callback: Function): void;
    (name: 'database::success', text: string, callback: Function): void;
    (name: 'findDatabase::instantSearch', text: string, callback: Function): void;
    (name: 'findDatabase::table::RFB::CERTIDAO', text: string, callback: Function): void;
    (name: 'logs::onerror', text: string, callback: Function): void;
    (name: 'serverCommunication::websocket::authentication', text: string, callback: Function): void;
    (name: 'serverCommunication::websocket::credits', text: string, callback: Function): void;
    (name: 'serverCommunication::websocket::sendMessage', text: string, callback: Function): void;
    (name: 'softphone::connected', text: string, callback: Function): void;
    (name: 'softphone::disconnected', text: string, callback: Function): void;
    (name: 'softphone::registered', text: string, callback: Function): void;
    (name: 'softphone::registrationFailed', text: string, callback: Function): void;
    (name: 'softphone::unregistered', text: string, callback: Function): void;
}

export interface RegisterBootstrapSignatures<T> {
    (name: 'analytics::google', callback: Function): T;
    (name: 'antiphishing::implement', callback: Function): T;
    (name: 'authentication::cordova::clear', callback: Function): T;
    (name: 'billingInformation', callback: Function): T;
    (name: 'bootstrap::end', callback: Function): T;
    (name: 'cordova', callback: Function): T;
    (name: 'credits', callback: Function): T;
    (name: 'databaseSearch', callback: Function): T;
    (name: 'demonstrate', callback: Function): T;
    (name: 'download', callback: Function): T;
    (name: 'dropzone', callback: Function): T;
    (name: 'email-activation', callback: Function): T;
    (name: 'endpoint', callback: Function): T;
    (name: 'facebook::track', callback: Function): T;
    (name: 'forgotPassword', callback: Function): T;
    (name: 'i18n', callback: Function): T;
    (name: 'iframeEmbed::open', callback: Function): T;
    (name: 'iframeEmbed::whitelabel', callback: Function): T;
    (name: 'inbox', callback: Function): T;
    (name: 'iugu::init', callback: Function): T;
    (name: 'mainSearch', callback: Function): T;
    (name: 'manifest', callback: Function): T;
    (name: 'module', callback: Function): T;
    (name: 'oauth', callback: Function): T;
    (name: 'parserCbusca', callback: Function): T;
    (name: 'parserCCbusca', callback: Function): T;
    (name: 'parserCCF', callback: Function): T;
    (name: 'parserIEPTB', callback: Function): T;
    (name: 'parserRFBCNPJ', callback: Function): T;
    (name: 'password', callback: Function): T;
    (name: 'remote-debug', callback: Function): T;
    (name: 'site::buttons', callback: Function): T;
    (name: 'site::carrousel', callback: Function): T;
    (name: 'softphone', callback: Function): T;
    (name: 'subaccount', callback: Function): T;
    (name: 'urlParameter', callback: Function): T;
    (name: 'watch::onerror', callback: Function): T;
}

export interface RegisterCallSignatures<T> {
    (name: 'accountOverview::dataset', callback: Function): T;
    (name: 'accountOverview::download', callback: Function): T;
    (name: 'accountOverview::filter', callback: Function): T;
    (name: 'accountOverview', callback: Function): T;
    (name: 'admin::autocompleteCreateCompany', callback: Function): T;
    (name: 'admin::changeAddress', callback: Function): T;
    (name: 'admin::changeCompany', callback: Function): T;
    (name: 'admin::changeContract', callback: Function): T;
    (name: 'admin::changeHide', callback: Function): T;
    (name: 'admin::changePassword', callback: Function): T;
    (name: 'admin::commercialReference', callback: Function): T;
    (name: 'admin::contactTypes', callback: Function): T;
    (name: 'admin::createAccount::formDescription', callback: Function): T;
    (name: 'admin::createCompany', callback: Function): T;
    (name: 'admin::email', callback: Function): T;
    (name: 'admin::fillCompanyAutocomplete', callback: Function): T;
    (name: 'admin::fillCompanysAutocomplete', callback: Function): T;
    (name: 'admin::index', callback: Function): T;
    (name: 'admin::message', callback: Function): T;
    (name: 'admin::openCompanys', callback: Function): T;
    (name: 'admin::phone', callback: Function): T;
    (name: 'admin::remove::email', callback: Function): T;
    (name: 'admin::remove::phone', callback: Function): T;
    (name: 'admin::report::dataset', callback: Function): T;
    (name: 'admin::report::download', callback: Function): T;
    (name: 'admin::report::filter', callback: Function): T;
    (name: 'admin::report', callback: Function): T;
    (name: 'admin::roleTypes', callback: Function): T;
    (name: 'admin::tag::create', callback: Function): T;
    (name: 'admin::tags::view', callback: Function): T;
    (name: 'admin::tags', callback: Function): T;
    (name: 'admin::tagsViewer', callback: Function): T;
    (name: 'admin::trigger', callback: Function): T;
    (name: 'admin::viewCompany', callback: Function): T;
    (name: 'alert', callback: Function): T;
    (name: 'authentication::authenticate', callback: Function): T;
    (name: 'authentication::force', callback: Function): T;
    (name: 'authentication::loggedin', callback: Function): T;
    (name: 'authentication::logout', callback: Function): T;
    (name: 'authentication::need', callback: Function): T;
    (name: 'authentication::unsetSessionId', callback: Function): T;
    (name: 'autocomplete', callback: Function): T;
    (name: 'bankAccount::need', callback: Function): T;
    (name: 'bankAccount::update', callback: Function): T;
    (name: 'billingInformation::changeAddress', callback: Function): T;
    (name: 'billingInformation::force', callback: Function): T;
    (name: 'billingInformation::need', callback: Function): T;
    (name: 'bipbop::createAccount::submit', callback: Function): T;
    (name: 'bipbop::createAccount', callback: Function): T;
    (name: 'blockui', callback: Function): T;
    (name: 'buyit', callback: Function): T;
    (name: 'ccbusca::enable', callback: Function): T;
    (name: 'ccbusca::parse', callback: Function): T;
    (name: 'ccbusca', callback: Function): T;
    (name: 'changePassword', callback: Function): T;
    (name: 'confirm', callback: Function): T;
    (name: 'credits::buy', callback: Function): T;
    (name: 'credits::charge::bankSlip', callback: Function): T;
    (name: 'credits::charge::creditCard', callback: Function): T;
    (name: 'credits::charge', callback: Function): T;
    (name: 'credits::get', callback: Function): T;
    (name: 'credits::has', callback: Function): T;
    (name: 'data::company', callback: Function): T;
    (name: 'databaseSearch::submit', callback: Function): T;
    (name: 'default::page', callback: Function): T;
    (name: 'download', callback: Function): T;
    (name: 'endpoint', callback: Function): T;
    (name: 'error::ajax', callback: Function): T;
    (name: 'error::server', callback: Function): T;
    (name: 'forgotPassword::code', callback: Function): T;
    (name: 'forgotPassword', callback: Function): T;
    (name: 'form::callback', callback: Function): T;
    (name: 'form', callback: Function): T;
    (name: 'generateRelations::createAdapter', callback: Function): T;
    (name: 'generateRelations', callback: Function): T;
    (name: 'geolocation', callback: Function): T;
    (name: 'getCreditCard', callback: Function): T;
    (name: 'i18n', callback: Function): T;
    (name: 'iframeEmbed::open', callback: Function): T;
    (name: 'iframeEmbed', callback: Function): T;
    (name: 'inboundMarketing::create', callback: Function): T;
    (name: 'inboundMarketing::open', callback: Function): T;
    (name: 'inboundMarketing', callback: Function): T;
    (name: 'inbox::check', callback: Function): T;
    (name: 'inbox::open', callback: Function): T;
    (name: 'inbox', callback: Function): T;
    (name: 'instantSearch', callback: Function): T;
    (name: 'iugu::requestPaymentToken', callback: Function): T;
    (name: 'link::register', callback: Function): T;
    (name: 'link', callback: Function): T;
    (name: 'loader::ajax', callback: Function): T;
    (name: 'loader::catchElement', callback: Function): T;
    (name: 'loader::register', callback: Function): T;
    (name: 'loader::unregister', callback: Function): T;
    (name: 'modal', callback: Function): T;
    (name: 'module', callback: Function): T;
    (name: 'moreResults', callback: Function): T;
    (name: 'oauth::call', callback: Function): T;
    (name: 'oauth::data', callback: Function): T;
    (name: 'oauth::result', callback: Function): T;
    (name: 'parent', callback: Function): T;
    (name: 'password::change', callback: Function): T;
    (name: 'price::create', callback: Function): T;
    (name: 'price::list', callback: Function): T;
    (name: 'price::update', callback: Function): T;
    (name: 'progress::init', callback: Function): T;
    (name: 'progress::ui::noblock', callback: Function): T;
    (name: 'progress::update', callback: Function): T;
    (name: 'report', callback: Function): T;
    (name: 'result::import', callback: Function): T;
    (name: 'result', callback: Function): T;
    (name: 'section', callback: Function): T;
    (name: 'selectedResults', callback: Function): T;
    (name: 'site::buttons', callback: Function): T;
    (name: 'site::carrousel', callback: Function): T;
    (name: 'softphone::call', callback: Function): T;
    (name: 'softphone::configuration', callback: Function): T;
    (name: 'softphone::configure', callback: Function): T;
    (name: 'softphone::disconnect', callback: Function): T;
    (name: 'softphone::keypad', callback: Function): T;
    (name: 'softphone::terminateCalls', callback: Function): T;
    (name: 'softphone::xirsys', callback: Function): T;
    (name: 'softphone', callback: Function): T;
    (name: 'subaccount::create', callback: Function): T;
    (name: 'subaccount::formDescription', callback: Function): T;
    (name: 'subaccount::limit', callback: Function): T;
    (name: 'subaccount::list', callback: Function): T;
    (name: 'takePicture', callback: Function): T;
    (name: 'timeline', callback: Function): T;
    (name: 'tooltip', callback: Function): T;
    (name: 'welcomescreen::email', callback: Function): T;
    (name: 'welcomescreen::putemail', callback: Function): T;
    (name: 'welcomescreen::wizard::1', callback: Function): T;
    (name: 'welcomescreen::wizard::2', callback: Function): T;
    (name: 'welcomescreen::wizard', callback: Function): T;
    (name: 'xmlDocument', callback: Function): T;
}

export interface TriggerSignatures<T> {
    (name: 'admin::commercialReference', reportModel: ReportModel, obj: undefined): T;
    (name: 'admin::tagsViewer', reportModel: ReportModel, obj: undefined): T;
    (name: 'admin::viewCompany', obj1: { actions: JQuery<HTMLElement>, companyNode: Element, section: JQuery<HTMLElement>, username: string }, obj2: undefined): T;
    (name: 'admin::viewCompany', obj1: { actions: JQuery<HTMLElement>, companyNode: JQuery<HTMLElement>, section: JQuery<HTMLElement>, username: string }, obj2: undefined): T;
    (name: 'admin', obj1: undefined, obj2: undefined): T;
    (name: 'authentication::authenticated::end', obj1: undefined, obj2: undefined): T;
    (name: 'authentication::authenticated', obj: undefined, callback: Function): T;
    (name: 'bootstrap::end', obj1: undefined, obj2: undefined): T;
    (name: 'call::admin::changeAddress', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::changeCompany', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::changeContract', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::commercialReference', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::contactTypes', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::email', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::fillCompanyAutocomplete', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::fillCompanysAutocomplete', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::index', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::openCompanys', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::phone', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::remove::email', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::remove::phone', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::report::dataset', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::report::filter', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::report', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::roleTypes', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::tag::create', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::tags::view', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::tags', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::tagsViewer', array: Array<any>, obj: undefined): T;
    (name: 'call::admin::viewCompany', array: Array<any>, obj: undefined): T;
    (name: 'call::authentication::loggedin', array: Array<any>, obj: undefined): T;
    (name: 'call::authentication::need', array: Array<any>, obj: undefined): T;
    (name: 'call::autocomplete', array: Array<any>, obj: undefined): T;
    (name: 'call::billingInformation::changeAddress', array: Array<any>, obj: undefined): T;
    (name: 'call::billingInformation::force', array: Array<any>, obj: undefined): T;
    (name: 'call::billingInformation::need', array: Array<any>, obj: undefined): T;
    (name: 'call::credits::buy', array: Array<any>, obj: undefined): T;
    (name: 'call::default::page', array: Array<any>, obj: undefined): T;
    (name: 'call::error::ajax', array: Array<any>, obj: undefined): T;
    (name: 'call::form', array: Array<any>, obj: undefined): T;
    (name: 'call::i18n', array: Array<any>, obj: undefined): T;
    (name: 'call::iframeEmbed', array: Array<any>, obj: undefined): T;
    (name: 'call::inbox::check', array: Array<any>, obj: undefined): T;
    (name: 'call::inbox::open', array: Array<any>, obj: undefined): T;
    (name: 'call::inbox', array: Array<any>, obj: undefined): T;
    (name: 'call::instantSearch', array: Array<any>, obj: undefined): T;
    (name: 'call::link', array: Array<any>, obj: undefined): T;
    (name: 'call::loader::ajax', array: Array<any>, obj: undefined): T;
    (name: 'call::loader::catchElement', array: Array<any>, obj: undefined): T;
    (name: 'call::loader::register', array: Array<any>, obj: undefined): T;
    (name: 'call::loader::unregister', array: Array<any>, obj: undefined): T;
    (name: 'call::modal', array: Array<any>, obj: undefined): T;
    (name: 'call::moreResults', array: Array<any>, obj: undefined): T;
    (name: 'call::register::accountOverview::dataset', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::accountOverview::download', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::accountOverview::filter', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::accountOverview', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::autocompleteCreateCompany', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::changeAddress', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::changeCompany', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::changeContract', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::changeHide', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::changePassword', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::commercialReference', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::contactTypes', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::createAccount::formDescription', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::createCompany', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::email', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::fillCompanyAutocomplete', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::fillCompanysAutocomplete', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::index', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::message', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::openCompanys', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::phone', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::remove::email', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::remove::phone', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::report::dataset', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::report::download', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::report::filter', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::report', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::roleTypes', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::tag::create', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::tags::view', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::tags', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::tagsViewer', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::trigger', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::admin::viewCompany', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::alert', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::authentication::authenticate', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::authentication::force', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::authentication::loggedin', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::authentication::logout', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::authentication::need', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::authentication::unsetSessionId', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::autocomplete', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::bankAccount::need', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::bankAccount::update', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::billingInformation::changeAddress', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::billingInformation::force', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::billingInformation::need', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::bipbop::createAccount::submit', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::bipbop::createAccount', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::blockui', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::buyit', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::ccbusca::enable', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::ccbusca::parse', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::ccbusca', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::changePassword', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::confirm', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::credits::buy', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::credits::charge::bankSlip', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::credits::charge::creditCard', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::credits::charge', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::credits::get', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::credits::has', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::data::company', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::databaseSearch::submit', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::default::page', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::download', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::endpoint', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::error::ajax', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::error::server', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::forgotPassword::code', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::forgotPassword', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::form::callback', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::form', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::generateRelations::createAdapter', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::generateRelations', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::geolocation', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::getCreditCard', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::i18n', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::iframeEmbed::open', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::iframeEmbed', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::inboundMarketing::create', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::inboundMarketing::open', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::inboundMarketing', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::inbox::check', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::inbox::open', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::inbox', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::instantSearch', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::iugu::requestPaymentToken', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::link::register', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::link', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::loader::ajax', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::loader::catchElement', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::loader::register', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::loader::unregister', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::modal', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::module', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::moreResults', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::oauth::call', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::oauth::data', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::oauth::result', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::parent', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::password::change', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::price::create', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::price::list', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::price::update', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::progress::init', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::progress::ui::noblock', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::progress::update', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::report', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::result::import', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::result', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::section', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::selectedResults', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::site::buttons', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::site::carrousel', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::call', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::configuration', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::configure', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::disconnect', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::keypad', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::terminateCalls', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone::xirsys', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::softphone', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::subaccount::create', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::subaccount::formDescription', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::subaccount::limit', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::subaccount::list', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::takePicture', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::timeline', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::tooltip', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::welcomescreen::email', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::welcomescreen::putemail', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::welcomescreen::wizard::1', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::welcomescreen::wizard::2', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::welcomescreen::wizard', obj1: undefined, obj2: undefined): T;
    (name: 'call::register::xmlDocument', obj1: undefined, obj2: undefined): T;
    (name: 'call::report', array: Array<any>, obj: undefined): T;
    (name: 'call::result', array: Array<any>, obj: undefined): T;
    (name: 'call::section', array: Array<any>, obj: undefined): T;
    (name: 'call::site::buttons', array: Array<any>, obj: undefined): T;
    (name: 'call::site::carrousel', array: Array<any>, obj: undefined): T;
    (name: 'call::subaccount::list', array: Array<any>, obj: undefined): T;
    (name: 'call::tooltip', array: Array<any>, obj: undefined): T;
    (name: 'findDatabase::instantSearch', array: Array<any>, callback: Function): T;
    (name: 'message', messageEvent: MessageEvent, obj: undefined): T;
    (name: 'plugin::authenticated', obj1: undefined, obj2: undefined): T;
    (name: 'serverCommunication::call', array: Array<any>, obj: undefined): T;
    (name: 'serverCommunication::responseComplete', array: Array<any>, obj: undefined): T;
    (name: 'serverCommunication::websocket::authentication::end', obj1: { adminOf: Array<any>, apiKey: string, cnpj: string, commercialReference: string, contractAccepted: boolean, contrato: Array<any>, cpf: string, credits: number, 'day-limit': number, email: Array<any>, emailUnchecked: boolean, endereco: Array<any>, geocode: { address_components: Array<any>, formatted_address: string, geometry: { bounds: { northeast: { lat: number, lng: number }, southwest: { lat: number, lng: number } }, location: { lat: number, lng: number }, location_type: string, viewport: { northeast: { lat: number, lng: number }, southwest: { lat: number, lng: number } } }, place_id: string, types: Array<any> }, limit: number, nome: string, postPaid: boolean, responsavel: string, status: number, tags: Array<any>, telefone: Array<any>, username: string }, obj2: undefined): T;
    (name: 'serverCommunication::websocket::authentication', obj1: { adminOf: Array<any>, apiKey: string, cnpj: string, commercialReference: string, contractAccepted: boolean, contrato: Array<any>, cpf: string, credits: number, 'day-limit': number, email: Array<any>, emailUnchecked: boolean, endereco: Array<any>, geocode: { address_components: Array<any>, formatted_address: string, geometry: { bounds: { northeast: { lat: number, lng: number }, southwest: { lat: number, lng: number } }, location: { lat: number, lng: number }, location_type: string, viewport: { northeast: { lat: number, lng: number }, southwest: { lat: number, lng: number } } }, place_id: string, types: Array<any> }, limit: number, nome: string, postPaid: boolean, responsavel: string, status: number, tags: Array<any>, telefone: Array<any>, username: string }, obj2: undefined): T;
    (name: 'serverCommunication::websocket::credits', obj1: { credits: number, receipt: { _id: string, company: { $id: string, $ref: string }, credits: { after: number, before: number }, date: number, description: string, for: { $id: string, $ref: string }, forRole: string, quantity: number, role: string, server: { SERVER_HOSTNAME: string, SERVER_PID: number }, tag: string, total: number, uniq: string, value: number } }, obj2: undefined): T;
    (name: 'serverCommunication::websocket::event', messageEvent: MessageEvent, obj: undefined): T;
    (name: 'serverCommunication::websocket::open', webSocket: WebSocket, obj: undefined): T;
}

export interface ClickSignatures<T> {
    (name: 'admin::changeAddress', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::changeCompany', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::changeContract', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
    (name: 'admin::email', text: string, element: JQuery<HTMLElement>): void;
    (name: 'admin::phone', text: string, element: JQuery<HTMLElement>): void;
    (name: 'admin::tags', text: string): void;
    (name: 'subaccount::list', element1: JQuery<HTMLElement>, text: string, element2: JQuery<HTMLElement>): void;
}
